name: publish

on:
  push:
    branches:
      - develop
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
#        os: ['ubuntu-latest', 'windows-latest', 'macos-latest', , 'ubuntu-22.04']
#        os: ['ubuntu-22.04-arm', 'ubuntu-24.04-arm']
#        os: ['ubuntu-22.04', 'ubuntu-24.04']
        os: ['ubuntu-24.04-arm']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Show the input string and matrix
        run: |
          echo "The raw input string is: ${{ inputs.platforms }}"
          echo "The matrix os value is: ${{ matrix.os }}"
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show runner OS
        run: echo "Building on ${{ runner.os }}"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.13.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          # Use the correct runner label to conditionally install aarch64 target
          targets: ${{ contains(matrix.os, 'macos') && 'aarch64-apple-darwin' || '' }}

      - name: Install Linux dependencies (Ubuntu only NOT ARM)
        if: contains(matrix.os, 'ubuntu') && !contains(runner.arch, 'arm')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            desktop-file-utils appstream

      - name: Install Linux dependencies (Ubuntu ARM only)
        if: contains(matrix.os, 'ubuntu') && contains(runner.arch, 'arm')
        run: |
          sudo apt update # It's good practice to run this first
          sudo apt install -y \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev:arm64 \
            \            
            libwebkit2gtk-4.1-dev:arm64 \
            libayatana-appindicator3-dev:arm64 \
            librsvg2-dev:arm64 \
            \
            patchelf \
            desktop-file-utils appstream

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      # Helpful diagnostics before building (kept non-fatal)
      - name: Tauri environment info (debug)
        run: pnpm tauri info || true

      - name: Set verbose build logs
        run: |
          echo "CARGO_TERM_VERBOSE=true" >> $GITHUB_ENV
          echo "RUST_LOG=tauri_bundler=trace,tauri_cli=debug" >> $GITHUB_ENV
          echo "TAURI_LOG_LEVEL=debug" >> $GITHUB_ENV

      - name: Build and publish with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: --verbose

      # If bundling fails, these help pinpoint missing libraries/binaries.
      - name: Inspect built binary (debug on failure)
        if: failure()
        run: |
          find src-tauri/target/release -maxdepth 2 -type f -name "tauri-*" -print || true
          ldd src-tauri/target/release/tauri-* || true
          which appstreamcli || true
          appstreamcli --version || true
          which desktop-file-validate || true
          echo 'SMTEST: AppStream'
          ldconfig -p | grep -E 'fuse|webkit' || true